// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpDz2RbH0KvkPPVDEiVv2pb7AuYvB0Jy4',
    appId: '1:503957087952:web:19db5b05f0605146e760d5',
    messagingSenderId: '503957087952',
    projectId: 'ai-secretary-5d72e',
    authDomain: 'ai-secretary-5d72e.firebaseapp.com',
    storageBucket: 'ai-secretary-5d72e.firebasestorage.app',
    measurementId: 'G-4100F2V331',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4FUKmhRh6IHlPtN4Rg1oyM3EiULb3dM',
    appId: '1:503957087952:android:0261c523a30c2e24e760d5',
    messagingSenderId: '503957087952',
    projectId: 'ai-secretary-5d72e',
    storageBucket: 'ai-secretary-5d72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GtMDrJfEeWCYohtCCFtu4KFNbPl2Lnw',
    appId: '1:503957087952:ios:8c9c83e110df9e41e760d5',
    messagingSenderId: '503957087952',
    projectId: 'ai-secretary-5d72e',
    storageBucket: 'ai-secretary-5d72e.firebasestorage.app',
    iosBundleId: 'com.example.aiSecretary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1GtMDrJfEeWCYohtCCFtu4KFNbPl2Lnw',
    appId: '1:503957087952:ios:8c9c83e110df9e41e760d5',
    messagingSenderId: '503957087952',
    projectId: 'ai-secretary-5d72e',
    storageBucket: 'ai-secretary-5d72e.firebasestorage.app',
    iosBundleId: 'com.example.aiSecretary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpDz2RbH0KvkPPVDEiVv2pb7AuYvB0Jy4',
    appId: '1:503957087952:web:93f30efc59f67533e760d5',
    messagingSenderId: '503957087952',
    projectId: 'ai-secretary-5d72e',
    authDomain: 'ai-secretary-5d72e.firebaseapp.com',
    storageBucket: 'ai-secretary-5d72e.firebasestorage.app',
    measurementId: 'G-4W5CG346B4',
  );
}
